### ISSUE TITLE
✨ToDo

### ISSUE THREAD

**Issue by stonesaw** [stonesaw/midi-planet-front#1]
## コンポ
- [x] #16
- [ ] #17
- [ ] #18

## ページ
- [ ] ホームページ (LP) `/` 
- [ ] 探す(SNS要素) `/explore`
- [x] #25
- [x] #28
- [x] #27
  - [ ] 新規作成 `/create`
  - [ ] 編集 `/edit/[pid]`
- [ ] 利用規約 `/terms-of-service`
- [ ] プライバシーポリシー `/privacy-policy`
- [ ] サイトマップ `/sitemap.xml`
- [ ] クローラーDoc `/robots.txt`
 
## 認証システム
- [x] #23

## エディター
- [x] #2
- [ ] OGP生成
- [ ] ルーティングの拡張
  - 新規作成 `/editor`
  - 編集 `/editor/[uid]`
- [x] #12
- [ ] EditorHeader
- [ ] MoviePreview
  - [x] #8 
  - [x] #9 
  - [x] #20
  - [ ] ドラムトラック
- [x] #4 
  - [ ] #30
- [x] #21
- [ ] mp4 出力
